#!/bin/sh
set -euo pipefail

BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${BASE_DIR}/.."
README_FILE="${REPO_DIR}/README.md"
UP_FILE="${REPO_DIR}/scripts/up.sh"
UP_REDASH_FILE="${REPO_DIR}/scripts/up_redash.sh"
UP_SUPERSET_FILE="${REPO_DIR}/scripts/up_superset.sh"
DOWN_FILE="${REPO_DIR}/scripts/down.sh"
DOWN_REDASH_FILE="${REPO_DIR}/scripts/down_redash.sh"
DOWN_SUPERSET_FILE="${REPO_DIR}/scripts/down_superset.sh"

reset_out_file() {
    local OUT_FILE=$1
    cat <<EOT >${OUT_FILE}
#!/bin/sh
# This file is autogenerated - DO NOT EDIT!
set -euo pipefail
BASE_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="\${BASE_DIR}/.."
(
cd \${REPO_DIR}
EOT
}

update_up() {
    local OUT_FILE=$UP_FILE
    reset_out_file ${OUT_FILE}
    awk '/^(kubectl create)/' $README_FILE >>$OUT_FILE
    awk '/^(kubectl apply)/' $README_FILE >>$OUT_FILE
    awk '/^(helm repo)/' $README_FILE | uniq >>$OUT_FILE
    awk '/^(helm upgrade)/' $README_FILE >>$OUT_FILE
    echo ")" >>$OUT_FILE
}

update_up_redash() {
    cat $UP_FILE | sed '/superset/d' >$UP_REDASH_FILE
}

update_up_superset() {
    cat $UP_FILE | sed '/redash/d' >$UP_SUPERSET_FILE
}

update_down() {
    local OUT_FILE=$DOWN_FILE
    reset_out_file ${OUT_FILE}
    awk '/^(helm uninstall)/' $README_FILE >>$OUT_FILE
    awk '/^(kubectl delete)/' $README_FILE >>$OUT_FILE
    echo ")" >>$OUT_FILE
}

update_down_redash() {
    cat $DOWN_FILE | sed '/superset/d' >$DOWN_REDASH_FILE
}

update_down_superset() {
    cat $DOWN_FILE | sed '/redash/d' >$DOWN_SUPERSET_FILE
}

main() {
    echo "Updating $UP_FILE"
    update_up
    echo "Updating $UP_REDASH_FILE"
    update_up_redash
    echo "Updating $UP_SUPERSET_FILE"
    update_up_superset
    echo "Updating $DOWN_FILE"
    update_down
    echo "Updating $DOWN_REDASH_FILE"
    update_down_redash
    echo "Updating $DOWN_SUPERSET_FILE"
    update_down_superset
}

main
